environment:
  release_version: '1.0.0'
  release_assembly_version: '1.0.0.0'
  
version: '$(release_version)+{build}'
os: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(release_assembly_version)'
  assembly_file_version: '$(release_assembly_version)'
  assembly_informational_version: '$(release_version)'
before_build:
- cmd: >-
    nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test:
  assemblies: '**\*.Tests.dll'
artifacts:
- path: \*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: oy2c6eta23bh6aunua2q64bd6mjklcgupnsuhtrtclrl3u
  on:
    branch: master 